version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "event-processing-demo"
s3_prefix = "event-processing-demo"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9xdmuwwqklct"
parameter_overrides = "DataStoreTableName=\"user_services\""
